services:
  cardano-utxo-monitor:
    container_name: cardano-utxo-monitor
    build: .
    restart: on-failure
    volumes:
      - cardano-compose-stacks-main_node-ipc:/ipc
      - ./resources:/config
      - utxo-monitor-data:/data
      - ./logs:/app/logs
    ports:
      - "18091:8091"
    command: [
      "--config-path", "/config/conf.json",
      "--log4rs-path", "/config/log4rs.yaml",
      "--host", "0.0.0.0",
      "--port", "8091"
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - cardano_network

volumes:
  cardano-compose-stacks-main_node-ipc:
    external: true
  utxo-monitor-data:

networks:
  cardano_network:
    name: cardano-compose-stacks-main_default
    external: true