services:
  cardano-utxo-monitor:
    container_name: cardano-utxo-monitor
    build:
      context: .
    depends_on:
      cardano-node:
        condition: service_healthy
    restart: on-failure
    volumes:
      - node-ipc:/ipc
      - ./resources:/config
      - utxo-monitor-data:/data
      - utxo-monitor-logs:/app/logs
    ports:
      - "8091:8091"
    command: [
      "--config-path", "/config/conf.json",
      "--log4rs-path", "/config/log4rs.yaml",
      "--host", "0.0.0.0",
      "--port", "8091"
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-ipc:
    external: true
  utxo-monitor-data:
  utxo-monitor-logs: