[package]
name = "bloom-offchain"
version = "1.0.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-primitives = { version = "0.1.0", path = "../concurrent-primitives" }
spectrum-offchain = { version = "0.1.0", path = "../spectrum-offchain" }
algebra-core = { version = "0.1.0", path = "../algebra-core" }
futures = "0.3.25"
log = "0.4.17"
bignumber = "0.1.1"
rand = { version = "0.8.5", features = ["small_rng"] }
type-equalities = "0.3.1"
serde = { version = "1.0.147", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["full"] }
nonempty = "0.10.*"
hex = "0.4.3"
num-rational = "0.4.1"
either = "1.9.0"
primitive-types = "0.12.2"
void = "1.0.2"
num-bigint = "0.4.6"
bigdecimal = "0.4.3"

[dev-dependencies]
spectrum-cardano-lib = { version = "0.1.0", path = "../spectrum-cardano-lib" }