[package]
name = "cardano-mempool-sync"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-primitives = { version = "0.1.0", path = "../concurrent-primitives" }
async-stream = "0.3.3"
spectrum-offchain-cardano = { version = "1.0.0", path = "../spectrum-offchain-cardano" }
spectrum-offchain = { version = "0.1.0", path = "../spectrum-offchain" }
pallas-network = { git = "https://github.com/txpipe/pallas.git", tag = "v1.0.0-alpha.2" }
cml-crypto = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
cml-core = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0.47"