[package]
name = "spectrum-offchain-cardano"
version = "1.0.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spectrum-offchain = { version = "0.1.0", path = "../spectrum-offchain" }
algebra-core = { version = "0.1.0", path = "../algebra-core" }
bloom-offchain = { version = "1.0.0", path = "../bloom-offchain" }
cardano-explorer = { version = "0.1.0", path = "../cardano-explorer" }
cml-core = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
cardano-submit-api = { version = "0.1.0", path = "../cardano-submit-api" }
spectrum-cardano-lib = { version = "0.1.0", path = "../spectrum-cardano-lib" }
cml-crypto = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
cml-chain = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
cml-multi-era = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
pallas-network = { git = "https://github.com/txpipe/pallas.git", tag = "v1.0.0-alpha.2" }
futures = "0.3.25"
tokio = { version = "1.42.0", features = ["full"] }
log = "0.4.17"
dashu-base = "0.4.1"
dashu-float = "0.4.1"
rand = { version = "0.8.5", features = ["small_rng"] }
async-trait = "0.1.88"
async-stream = "0.3.5"
type-equalities = "0.3.1"
rmp-serde = "1.3.0"
serde = { version = "1.0.147", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["full"] }
rocksdb = "0.22.*"
serde_json = "1.0.88"
hex = "0.4.3"
primitive-types = "0.12.2"
num-rational = "0.4.1"
void = "1.0.2"
num-traits = "0.2.17"
num = "0.2.1"
bigdecimal = "0.4.3"
bignumber = "0.1.1"
cbor_event = "2.4.0"
uplc = "=1.1.12"
num-bigint = "0.4.6"

strum_macros = "0.24.3"

[dev-dependencies]
rocksdb = "0.22.*"
