[package]
name = "spectrum-cardano-lib"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spectrum-offchain = { version = "0.1.0", path = "../spectrum-offchain" }
algebra-core = { version = "0.1.0", path = "../algebra-core" }
cml-chain = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
cml-core = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
cml-crypto = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
cml-multi-era = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4" }
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "3.9.0"
hex = "0.4.3"
cbor_event = "2.4.0"
derive_more = { version = "1.0.0", features = ["full"] }
derivative = "2.2.0"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
num-rational = "0.4.1"
either = "1.9.0"
primitive-types = "0.12.2"
num = "0.4.1"
type-equalities = "0.3.1"
