[package]
name = "spectrum-offchain"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cml-chain = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "13c35772222fc46b26177a62726720502bdf21e4", optional = true }
futures = "0.3.25"
tokio = { version = "1.42.0", features = ["full"] }
log = "0.4.17"
async-trait = "0.1.88"
type-equalities = "0.3.1"
chrono = "0.4.28"
serde = { version = "1.0.147", features = ["derive"] }
priority-queue = "1.3.0"
bounded-integer = { version = "0.5.7", features = ["types", "serde1"] }
rand = "0.8.5"
derive_more = { version = "1.0.0", features = ["full"] }
bincode = "1.3"
rmp-serde = "1.3.0"
rocksdb = "0.22.*"
serde_json = "1.0.88"
serde_with = { version = "2.1", features = ["chrono_0_4"] }
futures-timer = "3.0.2"
async-std = "1.12"
num-rational = { version = "0.4.1", features = ["serde"] }
either = "1.9.0"
circular-buffer = "0.1.7"
async-stream = "0.3.6"

[dev-dependencies]
rocksdb = "0.22.*"
derive_more = { version = "1.0.0", features = ["full"] }