refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/main.log"
    encoder:
      pattern: "{d} - {l} - {m}{n} "
root:
  level: trace
  appenders:
    - requests